[phases.setup]
nixPkgs = ['nodejs-18_x', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'chmod -R 775 storage bootstrap/cache'
]

[start]
cmd = 'php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
